openapi: 3.1.0
info:
  title: Start Make Scenario
  version: 1.0.0
servers:
  - url: https://hook.eu2.make.com
paths:
  /y5ph88d26qy21ur4iogeqfmef71cqjxu:
    post:
      summary: Start het Make-scenario voor vastgoedcopy
      operationId: startScenario
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                trigger:
                  type: string
                  example: start_scenario
      responses:
        '200':
          description: Scenario gestart
        '401':
          description: Unauthorized
        '500':
          description: Serverfout
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-make-apikey

  schemas: {}
